# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-3790c7cc-1f5c-4b87-aa72-6b3b2c79a5f7";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-3790c7cc-1f5c-4b87-aa72-6b3b2c79a5f7".device =
    "/dev/disk/by-uuid/3790c7cc-1f5c-4b87-aa72-6b3b2c79a5f7";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/47CD-1A41";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-428b3e1c-f1fe-4502-875d-13da1c7ec348"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
